name: Awesome CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Building project with Gradle
        working-directory: .
        run: |
          chmod +x gradlew
          ./gradlew build -x test
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
        - uses: actions/checkout@v2

        - name: Set up JDK 8
          uses: actions/setup-java@v2
          with:
            java-version: '8'
            distribution: 'adopt'
        - name: Testing
          working-directory: .
          run: |
            chmod +x gradlew
            ./gradlew test
        - name: Run Test Coverage
          run: ./gradlew jacocoTestReport

        - name: generate jacoco badge
          uses: cicirello/jacoco-badge-generator@v2
          with:
            generate-branches-badge: true
